version: "3.6"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # For testing only
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    build: .
    image: ${CONTAINER_IMAGE:-todo-backend}
    volumes:
      - ./:/app/
    depends_on:
      - db
    environment:
      TODO_POSTGRES_DB: todo
      TODO_POSTGRES_HOST: db
      TODO_POSTGRES_USER: postgres
      TODO_POSTGRES_PASSWORD: postgres
    ports:
      - 4321:4321

volumes:
  postgres_volume:
