"""Users table

Revision ID: 63680ef9d5d5
Revises:
Create Date: 2022-11-06 00:15:14.920775

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '63680ef9d5d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.Unicode(length=32), nullable=False),
        sa.Column('_password', sa.Unicode(), nullable=False),
        sa.Column('type', sa.Unicode(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
